<?php

return [
    'families' => [
        'weightlifting' => [
            [
                'type' => 'one_rm',
                'reduce' => 'estimated1RM',
                'compare' => 'scalarBest',
                'field' => 'load',
                'repField' => 'reps',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'scalar',
                'label' => 'Est. 1RM',
                'format' => 'weight',
            ],
            [
                'type' => 'rep_specific',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['reps'],
                'aggregate' => 'maxValue',
                'valueField' => 'load',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByReps',
                'maxReps' => 10,
                'suppressDominated' => true,
                'label' => '{n}-rep max',
                'format' => 'weight',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumProduct',
                'compare' => 'scalarBest',
                'factors' => ['load', 'reps'],
                'unitField' => 'load',
                'direction' => 'max',
                'tolerance' => 'percent',
                'store' => 'scalar',
                'label' => 'Volume',
                'bodyweightLabel' => 'Total Reps',
                'format' => 'volume',
            ],
            [
                'type' => 'density',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['load'],
                'aggregate' => 'count',
                'requirePrevious' => true,
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByKey',
                'label' => 'Sets at {w}',
                'format' => 'sets',
            ],
            [
                'type' => 'hypertrophy',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['load'],
                'aggregate' => 'sumReps',
                'requirePrevious' => true,
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByKey',
                'label' => 'Reps at {w}',
                'format' => 'reps',
            ],
        ],
        'bodyweight' => [
            [
                'type' => 'rep_specific',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['reps'],
                'aggregate' => 'maxValue',
                'valueField' => 'load',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByReps',
                'maxReps' => 10,
                'suppressDominated' => true,
                'label' => '{n}-rep max',
                'format' => 'weight',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumProduct',
                'compare' => 'scalarBest',
                'factors' => ['load', 'reps'],
                'mode' => 'weighted',
                'unitField' => 'load',
                'direction' => 'max',
                'tolerance' => 'percent',
                'store' => 'scalar',
                'label' => 'Volume',
                'format' => 'volume',
            ],
            [
                'type' => 'bodyweight_volume',
                'reduce' => 'sumProduct',
                'compare' => 'scalarBest',
                'factors' => ['reps'],
                'mode' => 'bodyweight',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Total Reps',
                'format' => 'reps',
            ],
        ],
        'cardio' => [
            [
                'type' => 'endurance',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'distance',
                'store' => 'scalar',
                'label' => 'Longest Distance',
                'format' => 'distance',
            ],
            [
                // Cardio "distance per round": sumOf-of-distance keyed by round count — a generic
                // single-key record (store 'keyed'), not the weight rep-max shape. Aligned with the
                // Athlete descriptor.
                'type' => 'rep_specific',
                'reduce' => 'sumOf',
                'compare' => 'keyedBest',
                'keyFields' => ['rounds'],
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'distance',
                'store' => 'keyed',
                'label' => 'Best Distance per Round',
                'format' => 'distance',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumOf',
                'compare' => 'scalarBest',
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'distance',
                'store' => 'scalar',
                'label' => 'Total Distance',
                'format' => 'distance',
            ],
        ],
        'static_hold' => [
            [
                'type' => 'time',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'time',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Longest Hold',
                'format' => 'seconds',
            ],
            [
                'type' => 'consistency',
                'reduce' => 'minOf',
                'compare' => 'scalarBest',
                'field' => 'time',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'minGroupSize' => 2,
                'label' => 'Best Min Hold',
                'format' => 'seconds',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumOf',
                'compare' => 'scalarBest',
                'field' => 'time',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Total Time Held',
                'format' => 'seconds',
            ],
            [
                'type' => 'density',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['time'],
                'aggregate' => 'count',
                'requirePrevious' => true,
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'keyedByKey',
                'label' => 'Max Sets @ Duration',
                'format' => 'sets',
            ],
        ],
        'load_output' => [
            [
                'type' => 'load',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'load',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'scalar',
                'label' => 'Heaviest Load',
                'format' => 'weight',
            ],
            [
                'type' => 'distance',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Longest Distance',
                'format' => 'distance',
            ],
            [
                'type' => 'duration',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'duration',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Longest Duration',
                'format' => 'seconds',
            ],
            [
                'type' => 'speed',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['load', 'distance'],
                'aggregate' => 'minValue',
                'valueField' => 'duration',
                'direction' => 'min',
                'tolerance' => 'none',
                'requirePrevious' => true,
                'store' => 'keyedByKey',
                'label' => 'Fastest Time',
                'format' => 'seconds',
            ],
        ],
    ],

    // Maps a log_type OR exercise_type to its PR family. PrEngine::resolveFamily tries the log_type
    // first, then falls back to the exercise_type, so BOTH vocabularies are covered here. This must
    // stay aligned with the Athlete LOG_TYPE_TO_FAMILY (athlete/src/shared/logging/prDescriptors.js);
    // the cross-app family-resolution contract test asserts they agree for every key.
    'logTypeToFamily' => [
        // exercise_type values (Logger's derived type; used as the resolveFamily fallback)
        'regular' => 'weightlifting',
        'bodyweight' => 'bodyweight',
        'cardio' => 'cardio',
        'static_hold' => 'static_hold',
        'load_output' => 'load_output',

        // Athlete log_type values (what a synced exercise carries in log_type)
        'barbell' => 'weightlifting',
        'single-dumbbell' => 'weightlifting',
        'dual-dumbbell' => 'weightlifting',
        'kettlebell' => 'weightlifting',
        'ball' => 'weightlifting',
        'machine' => 'weightlifting',
        'bodyweight-reps' => 'bodyweight',
        'added-weight' => 'bodyweight',
        'cardio-distance' => 'cardio',
        'cardio-calories' => 'cardio',
        'static-hold' => 'static_hold',
        'dual-kettlebell' => 'static_hold',
        'sled' => 'load_output',
        'weighted-carry' => 'load_output',

        // banded: no PRs
        'banded' => null,
        'banded_resistance' => null,
        'banded_assistance' => null,
    ],
];
