<?php

return [
    'families' => [
        'weightlifting' => [
            [
                'type' => 'one_rm',
                'reduce' => 'estimated1RM',
                'compare' => 'scalarBest',
                'field' => 'weight',
                'repField' => 'reps',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'scalar',
                'label' => 'Est. 1RM',
                'format' => 'weight',
            ],
            [
                'type' => 'rep_specific',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['reps'],
                'aggregate' => 'maxValue',
                'valueField' => 'weight',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByReps',
                'maxReps' => 10,
                'suppressDominated' => true,
                'label' => '{n}-rep max',
                'format' => 'weight',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumProduct',
                'compare' => 'scalarBest',
                'factors' => ['weight', 'reps'],
                'unitField' => 'weight',
                'direction' => 'max',
                'tolerance' => 'percent',
                'store' => 'scalar',
                'label' => 'Volume',
                'bodyweightLabel' => 'Total Reps',
                'format' => 'volume',
            ],
            [
                'type' => 'density',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['weight'],
                'aggregate' => 'count',
                'requirePrevious' => true,
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByKey',
                'label' => 'Sets at {w}',
                'format' => 'sets',
            ],
            [
                'type' => 'hypertrophy',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['weight'],
                'aggregate' => 'sumReps',
                'requirePrevious' => true,
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByKey',
                'label' => 'Reps at {w}',
                'format' => 'reps',
            ],
        ],
        'bodyweight' => [
            [
                'type' => 'rep_specific',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['reps'],
                'aggregate' => 'maxValue',
                'valueField' => 'weight',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'keyedByReps',
                'maxReps' => 10,
                'suppressDominated' => true,
                'label' => '{n}-rep max',
                'format' => 'weight',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumProduct',
                'compare' => 'scalarBest',
                'factors' => ['weight', 'reps'],
                'unitField' => 'weight',
                'direction' => 'max',
                'tolerance' => 'percent',
                'store' => 'scalar',
                'label' => 'Volume',
                'bodyweightLabel' => 'Total Reps',
                'format' => 'volume',
            ],
        ],
        'cardio' => [
            [
                'type' => 'endurance',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'distance',
                'store' => 'scalar',
                'label' => 'Longest Distance',
                'format' => 'distance',
            ],
            [
                // Cardio "distance per round": sumOf-of-distance keyed by round count — a generic
                // single-key record (store 'keyed'), not the weight rep-max shape. Aligned with the
                // Athlete descriptor.
                'type' => 'rep_specific',
                'reduce' => 'sumOf',
                'compare' => 'keyedBest',
                'keyFields' => ['rounds'],
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'distance',
                'store' => 'keyed',
                'label' => 'Best Distance per Round',
                'format' => 'distance',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumOf',
                'compare' => 'scalarBest',
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'distance',
                'store' => 'scalar',
                'label' => 'Total Distance',
                'format' => 'distance',
            ],
        ],
        'static_hold' => [
            [
                'type' => 'time',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'time',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Longest Hold',
                'format' => 'seconds',
            ],
            [
                'type' => 'consistency',
                'reduce' => 'minOf',
                'compare' => 'scalarBest',
                'field' => 'time',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'minGroupSize' => 2,
                'label' => 'Best Min Hold',
                'format' => 'seconds',
            ],
            [
                'type' => 'volume',
                'reduce' => 'sumOf',
                'compare' => 'scalarBest',
                'field' => 'time',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Total Time Held',
                'format' => 'seconds',
            ],
            [
                'type' => 'density',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['time'],
                'aggregate' => 'count',
                'requirePrevious' => true,
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'keyedByKey',
                'label' => 'Max Sets @ Duration',
                'format' => 'sets',
            ],
        ],
        'load_output' => [
            [
                'type' => 'load',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'weight',
                'direction' => 'max',
                'tolerance' => 'unit',
                'store' => 'scalar',
                'label' => 'Heaviest Load',
                'format' => 'weight',
            ],
            [
                'type' => 'distance',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'distance',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Longest Distance',
                'format' => 'distance',
            ],
            [
                'type' => 'duration',
                'reduce' => 'maxOf',
                'compare' => 'scalarBest',
                'field' => 'duration',
                'direction' => 'max',
                'tolerance' => 'none',
                'store' => 'scalar',
                'label' => 'Longest Duration',
                'format' => 'seconds',
            ],
            [
                'type' => 'speed',
                'reduce' => 'perKey',
                'compare' => 'keyedBest',
                'keyFields' => ['weight', 'distance'],
                'aggregate' => 'minValue',
                'valueField' => 'duration',
                'direction' => 'min',
                'tolerance' => 'none',
                'requirePrevious' => true,
                'store' => 'keyedByKey',
                'label' => 'Fastest Time',
                'format' => 'seconds',
            ],
        ],
    ],

    'logTypeToFamily' => [
        'regular' => 'weightlifting',
        'bodyweight' => 'bodyweight',
        'cardio' => 'cardio',
        'static_hold' => 'static_hold',
        'sled' => 'load_output',
        'weighted-carry' => 'load_output',
        'banded' => null,
        'banded_resistance' => null,
        'banded_assistance' => null,
    ],
];
